RestoChoice/ViewModels/WelcomeViewModel.cs
using System;
using System.Collections.Generic;

namespace Survey.ViewModels
{
	public class WelcomeViewModel
	{
		public int Id { get; set; }
		public string Message { get; set; }
		public DateTime Date { get; set; }
		public List<Models.Restaurant> Restaurants { get; set; }
		public Models.Restaurant Restaurant { get; set; }
		public string Login { get; set; }
	}
}

RestoChoice/Controllers/RestaurantController.cs
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Survey.Models;

namespace Survey.Controllers
{
    public class RestaurantController : Controller
    {
        // GET: Restaurant
        public ActionResult Index()
        {
			using (IDal dal = new Dal())
			{
				List<Restaurant> allRestaurants = dal.GetAllRestaurants();
				return View(allRestaurants);
			}		
        }

		public ActionResult ModifyRestaurant(int? id)
		{
			if (id.HasValue)
			{
				using (IDal dal = new Dal())
				{
					Restaurant restaurant = dal.GetAllRestaurants().FirstOrDefault(r => r.Id == id);

					if (restaurant == null)
					{
						return HttpNotFound();
					}

					return View(restaurant);
				}
			}
			else
			{
				return View("Error");
			}
		}

		public ActionResult CreateRestaurant()
		{
			return View();
		}

		[HttpPost]
		public ActionResult CreateRestaurant(Restaurant resto)
		{
			using (IDal dal = new Dal())
			{
				if (dal.IsExistingRestaurant(resto.Name))
				{
					ModelState.AddModelError("Name", "This restaurant already exists");
					return View(resto);
				}
				else if (ModelState.IsValid)
				{
					dal.CreateRestaurant(resto.Name, resto.PhoneNumber);
					return RedirectToAction("Index");
				}
				else
				{
					return View(resto);
				}		
			}
		}

		[HttpPost]
		public ActionResult ModifyRestaurant(Restaurant resto)
		{
			if (ModelState.IsValid == false)
			{
				return View(resto);
			}

			using (IDal dal = new Dal())
			{
				dal.ModifyRestaurant(resto.Id, resto.Name, resto.PhoneNumber);

				return RedirectToAction("Index");
			}
		}
	}
}

RestoChoice/Controllers/WelcomeController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using Survey.Models;
using Survey.ViewModels;

namespace Survey.Controllers
{
    public class WelcomeController : Controller
    {
        // GET: Welcome
        public ActionResult Index()
        {

			return View(); 
        }

		[HttpPost]
		[ActionName("Index")]
		public ActionResult CreateSurvey()
		{
			using (IDal dal = new Dal())
			{
				int newSurveyId = dal.CreateSurvey();
				return RedirectToAction("Index", "Survey", new { id = newSurveyId });
			}
		}
    }
}

RestoChoice/Views/Welcome/Index.cshtml
@model Survey.ViewModels.WelcomeViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<style type="text/css">
    table {
        border-collapse: collapse;
    }

    td, th {
        border: 1px solid black;
    }
</style>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        Ready to choose a restaurant ?
    </div>
    @using (Html.BeginForm())
    {
        <input type="submit" value="Create a survey" />
    }
    <ul>
        <li>@Html.ActionLink("Add a restaurant", "CreateRestaurant", "Restaurant")</li>
        <li>@Html.ActionLink("Modify restaurants", "Index", "Restaurant")</li>
    </ul>
</body>
</html>